### PR TITLE
Olelensmar/fix/expand all kinds

### LINKED ISSUE #3806: "Expand All" resource kinds not always working
on top of the navigator - as Monokle internally looks at _all_ available resource kinds in all metaMaps to decide if it should expand or collapse - it should look only at those that are actually visible

### PR DESCRIPTION
**Pull request by olensmar**
This PR fixes #3806

## Changes

-

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [X] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

File: src/components/organisms/NavigatorPane/NavigatorPane.tsx [hunk 1]
```diff
@@ -120,16 +123,18 @@ export default NavPane;
 
 function CollapseAction() {
   const dispatch = useAppDispatch();
-  const allKinds = useAppSelector(resourceKindsSelector);
-  const collapsedKinds = useAppSelector(s => s.ui.navigator.collapsedResourceKinds);
+  // const activeStorage = useAppSelector(activeResourceStorageSelector);
```
Comment (devcatalin) [inline src/components/organisms/NavigatorPane/NavigatorPane.tsx:126]: you can delete this

File: src/components/organisms/NavigatorPane/NavigatorPane.tsx [hunk 2]
```diff
@@ -120,16 +123,18 @@ export default NavPane;
...
+  const navigatorKinds = useRefSelector(navigatorResourceKindsSelector);
+  const collapsedKinds = useRefSelector(s => s.ui.navigator.collapsedResourceKinds);
 
   const onClick = useCallback(() => {
-    if (collapsedKinds.length === allKinds.length) {
-      dispatch(expandResourceKinds(allKinds));
+    log.info('collapsing', navigatorKinds, collapsedKinds);
```
Comment (devcatalin) [inline src/components/organisms/NavigatorPane/NavigatorPane.tsx:131]: also delete this

**Review by devcatalin — CHANGES_REQUESTED** [review]

**Review by devcatalin — APPROVED** [review]
