### PR TITLE
fix: Kubeconfig path not changing

### LINKED ISSUE #2070: Kubeconfig path not changing
Changing kubeconfig path and then immediately closing the settings drawer will not trigger the update. 

We should maybe show a loading indicator until the new path is saved and prevent the user from being able to close the settings drawer.

### PR DESCRIPTION
**Pull request by sriniva7**
This PR...

## Changes

-  Under KUBECONFIG, *Browse Button* and *spinner* gets toggles based on the file that gets uploaded.

## Fixes
#2070 

## How to test it

- Create a project
- Select three dot in top right corner.
- Select setting and then under *Active Project* Browse file in KUBECONFIG
- You can see there will be spinner till the file gets uploaded

## Screenshots
- #### Before uploading the file
image

- ####  After selecting a file
image

- ####  After file gets uploaded
image

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by szmski — APPROVED** [review]

File: src/components/organisms/SettingsManager/Settings.tsx [hunk 1]
```diff
@@ -75,6 +78,8 @@ export const Settings = ({
     Boolean(!config?.kubeConfig?.path) || Boolean(!config?.kubeConfig?.isPathValid)
   );
   const [currentKubeConfig, setCurrentKubeConfig] = useState(config?.kubeConfig?.path);
+  const [currentKubeConfigInValue, setCurrentKubeConfigInValue] = useState(config?.kubeConfig?.path);
```
Comment (topliceanurazvan) [inline src/components/organisms/SettingsManager/Settings.tsx:81]: Why do we need to use this if we already have a `currentKubeConfig` ?

File: src/App.tsx [hunk 2]
```diff
@@ -88,6 +88,7 @@ const App = () => {
   const isFiltersPresetModalVisible = useAppSelector(state => state.ui.filtersPresetModal?.isOpen);
   const isInClusterMode = useAppSelector(isInClusterModeSelector);
   const isNewResourceWizardVisible = useAppSelector(state => state.ui.newResourceWizard.isOpen);
+  const isKubeConfigBrowseSettingOpen = useAppSelector(state => state.ui.kubeConfigBrowseSetting.isOpen);
```
Comment (topliceanurazvan) [inline src/App.tsx:91]: Lets name it with `Settings` instead of `Setting` and change accordingly all over the project

File: src/components/organisms/SettingsManager/Settings.tsx [hunk 3]
```diff
@@ -75,6 +78,8 @@ export const Settings = ({
...
+  const [spinBrowse, setspinBrowse] = useState(true);
```
Comment (topliceanurazvan) [inline src/components/organisms/SettingsManager/Settings.tsx:82]: Lets rename this to `isKubeConfigPathChanging`

File: src/redux/reducers/ui.ts [hunk 4]
```diff
@@ -222,6 +222,12 @@ export const uiSlice = createSlice({
     closeFolderExplorer: (state: Draft<UiState>) => {
       state.folderExplorer = {isOpen: false};
     },
+    closeKubeConfigBrowseSetting: (state: Draft<UiState>) => {
+      state.kubeConfigBrowseSetting = {isOpen: true};
```
Comment (topliceanurazvan) [inline src/redux/reducers/ui.ts:226]: Can't really understand what is the meaning of this action 🤔 The name is suggesting a close of the `kubeConfigBrowseSettings` but you are setting `isOpen` to true...

File: src/redux/reducers/ui.ts [hunk 5]
```diff
@@ -222,6 +222,12 @@ export const uiSlice = createSlice({
...
+    },
+    openKubeConfigBrowseSetting: (state: Draft<UiState>) => {
+      state.kubeConfigBrowseSetting = {isOpen: false};
```
Comment (topliceanurazvan) [inline src/redux/reducers/ui.ts:229]: Same as above

**Review by topliceanurazvan — CHANGES_REQUESTED** [review]
Left a couple of comments

File: src/redux/reducers/ui.ts (hunk 4 above)
Comment (sriniva7) [reply src/redux/reducers/ui.ts:226]: If you want to suggest me better naming convention then please do. (like instead of `isOpen` to `isClose` or any other)

I believe it is set the state, to check whether to close the `Drawer` or not. You can find the code in `App.tsx` component.

File: src/redux/reducers/ui.ts (hunk 5 above)
Comment (sriniva7) [reply src/redux/reducers/ui.ts:229]: If you want to suggest me better naming convention then please do. (like instead of `isOpen` to `isClose` or any other)

I believe it is set the state, to check whether to close the `Drawer` or not. You can  find the relevant code in `App.tsx` component.

File: src/components/organisms/SettingsManager/Settings.tsx (hunk 3 above)
Comment (sriniva7) [reply src/components/organisms/SettingsManager/Settings.tsx:82]: Okay

File: src/App.tsx (hunk 2 above)
Comment (sriniva7) [reply src/App.tsx:91]: Okay

File: src/components/organisms/SettingsManager/Settings.tsx (hunk 1 above)
Comment (sriniva7) [reply src/components/organisms/SettingsManager/Settings.tsx:81]: I believe `currentKubeConfig` is used in some other place called `useDebounce` . So I added a new state to solve the confusion.
image

Comment (topliceanurazvan) [reply src/components/organisms/SettingsManager/Settings.tsx:81]: Hmm, I think it doesn't change anything if it is used in `useDebounce`, we could still use it as the value for the input

File: src/redux/reducers/ui.ts (hunk 5 above)
Comment (topliceanurazvan) [reply src/redux/reducers/ui.ts:232]: You don't have to pass it from child to parent, just create a new property on redux store and use it across all the components

Comment (topliceanurazvan) [reply src/redux/reducers/ui.ts:232]: Similar to `kubeConfigBrowseSetting`

Comment (sriniva7) [reply src/redux/reducers/ui.ts:232]: okay

File: src/components/organisms/SettingsManager/Settings.tsx (hunk 1 above)
Comment (sriniva7) [reply src/components/organisms/SettingsManager/Settings.tsx:81]: This `currentKubeConfigInValue`, Is used to set the `kubeconfig path` in `input` field after path is set to all place in the component.

So it matches with time delay.

So it is up to you whether you want this implementation or not

File: src/components/organisms/SettingsManager/Settings.tsx [hunk 6]
```diff
@@ -98,15 +97,12 @@ export const Settings = ({
     setIsClusterActionDisabled(Boolean(!config?.kubeConfig?.path) || Boolean(!config?.kubeConfig?.isPathValid));
     setCurrentKubeConfig(config?.kubeConfig?.path);
     dispatch(openKubeConfigBrowseSetting());
-    setspinBrowse(false);
   }, [config?.kubeConfig]);
```
Comment (topliceanurazvan) [inline src/components/organisms/SettingsManager/Settings.tsx:100]:
```suggestion
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [config?.kubeConfig]);
```

File: src/components/organisms/SettingsManager/Settings.tsx [hunk 7]
```diff
@@ -98,15 +97,12 @@ export const Settings = ({
...
 
   useEffect(() => {
     // If config prop is changed externally, This code will make localConfig even with config prop
     setLocalConfig(config);
-    setCurrentKubeConfigInValue(currentKubeConfig);
     dispatch(closeKubeConfigBrowseSetting());
-    setspinBrowse(true);
   }, [config]);
```
Comment (topliceanurazvan) [inline src/components/organisms/SettingsManager/Settings.tsx:106]:
```suggestion
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [config]);
```

File: src/components/organisms/SettingsManager/Settings.tsx [hunk 8]
```diff
@@ -355,18 +349,18 @@ export const Settings = ({
...
             onClick={() => focusInput()}
-            value={currentKubeConfigInValue}
+            value={currentKubeConfig}
             onChange={onUpdateKubeconfig}
             disabled={isEditingDisabled}
           />
         </Tooltip>
         <Tooltip mouseEnterDelay={TOOLTIP_DELAY} title={BrowseKubeconfigTooltip} placement="right">
-          {spinBrowse && (
+          {isKubeConfigBrowseSettingsOpen && (
```
Comment (topliceanurazvan) [inline src/components/organisms/SettingsManager/Settings.tsx:358]: Here you could use the conditional `?`:

```
{isKubeConfigBrowseSettingsOpen ? 
  <S.Button> ...
  : 
  <ReloadOutlined> ...
}
```

**Review by topliceanurazvan — CHANGES_REQUESTED** [review]
Looks good, left a couple of suggestions

**Review by topliceanurazvan — APPROVED** [review]
Great work 🙌🏻
