### PR TITLE
fix: ensured passing of main process env to kubeclient exec authenticator

### LINKED ISSUE #1285: Use Paths for aws cli or aws-iam-authenticator for EKS AuthN - MacOS
**Describe the enhancement you'd like to see**
In my `.kube/config` I use either `aws eks get-token` or `aws-iam-authenticator` as the commands to authenticate to EKS clusters.

```
...
      args:
      - token
      - -i
      - monokle
      command: aws-iam-authenticator
...
```

or

```
...
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "monokle"
 ...
```

The tools that create the `user` elements in the `.kube/config` do not include the absolute paths for these binaries. My shell resolves the paths. It would be very handy for Monokle to resolve the paths as well. This would reduce troubleshooting, and the need to continually edit `kube/config` files `user` elements.

Without the absolute paths (`which aws` or `which aws-iam-authenticator`) the AuthN fails with the following error:
```
Error: Command failed with ENOENT: aws --region <REGION> eks get-token --cluster-name <CLUSTER_NAME> spawnSync aws ENOENT
```

### PR DESCRIPTION
**Pull request by olensmar**
This PR ensures that all kubeclient instances are created consistently - and ensures that kubeconfig users with exec authentication use the main process env for exec call

## Changes

-

## Fixes

#1285 

## How to test it

- create a context in kubeconfig that has a user that uses exec authentication (aws) - and attempt to preview this context in Monokle

## Screenshots

-

## Checklist

- [X] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

File: src/redux/reducers/main.ts [hunk 1]
```diff
@@ -202,6 +209,9 @@ export const mainSlice = createSlice({
   name: 'main',
   initialState: initialState.main,
   reducers: {
+    setMainProcessEnv: (state: Draft<AppState>, action: PayloadAction<any>) => {
+      mainProcessEnv = action.payload;
```
Comment (devcatalin) [inline src/redux/reducers/main.ts:213]: this is a bit weird, should we live it like this for now?

the alternative would be to create an ipc event and send that from main process instead of dispatching this action

File: src/utils/kubeclient.ts [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+  const path = typeof config === 'string' ? config : config.projectConfig?.kubeConfig?.path || config.kubeConfig.path;
+  if (!path) {
+    throw new Error('Missing path to kubeconfing');
+  }
+
+  kc.loadFromFile(path);
+  let currentContext =
+    context || typeof config === 'string'
+      ? undefined
+      : config.projectConfig?.kubeConfig?.currentContext || config.kubeConfig.currentContext;
```
Comment (devcatalin) [inline src/utils/kubeclient.ts:21]: shouldn't this be:
```  
let currentContext = typeof config === 'string'
      ? context
      : config.projectConfig?.kubeConfig?.currentContext || config.kubeConfig.currentContext;
```

File: src/redux/reducers/main.ts (hunk 1 above)
Comment (olensmar) [reply src/redux/reducers/main.ts:213]: that's what I had initially - i preferred this approach - but maybe an IPC event is easier to understand!?

File: src/utils/kubeclient.ts (hunk 2 above)
Comment (olensmar) [reply src/utils/kubeclient.ts:21]: yes - thanks

**Review by devcatalin — APPROVED** [review]
LGTM
